# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a9cc13d4a5cc894af0d4d624162aa2b3e942e630c0ac968ccc8fc27cade5197dee6ea62fbb1694eef2e574d2aca334b325b0c7838220bf4ba92c9aed235d334

test:
  secret_key_base: c903dd9b362f0fe0779b4db09706cc4aecc9b62d9106833e35ea2bc2d511a4988eb3c89186d2867326b27a58dc164867511c4c0121efb1178ac9a60cdebc1e75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
